export const FETCH_COURSES = "FETCH_COURSES";

export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";

export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";

export const START_LOADING = "START_LOADING";

export const STOP_LOADING = "STOP_LOADING";
